# Selfplay - Kyrgios
name: PhysicsSelfPlayController
test_name: SelfPlayControllerVis
env: 
  numEnvs: 2
  episodeLength: 300
  envSpacing: 5
  isFlagrun: False
  enableDebugVis: False
  powerScale: 1.0
  numAMPObsSteps: 10
  enableHistObs: False
  enableEarlyTermination: False

  physics:
    config: selfplayer 
    pretrained_model_cp: results/tennis_im/models/Kyrgios_latest.pth
    name: HumanoidSMPLIMMVAEDual
    test_name: HumanoidSMPLIMMVAEDual
    assetFileName: smpl_mesh_humanoid_federer.xml
    substeps: 6
    num_position_iterations: 2
    residual_force_scale: 31.85
    plane_restitution: 1.5

  vid2player:
    dual_mode: selfplay
    mvae_ver: kyrgios 
    player: kyrgios
    grip: eastern
    righthand: True
    court_min: [-5, -16]
    court_max: [5, -10]
    racket_friction: 0.8
    ball_friction: 0.2
    restitution: 0.9
    spin_scale: 5

    smpl_beta: [
          0.3303309679031372,
          0.2433803677558899,
          0.25490066409111023,
          -0.002098292112350464,
          -0.029715776443481445,
          -0.26090842485427856,
          -0.09222550690174103,
          0.2291903793811798,
          0.36660030484199524,
          0.1299755573272705
          ]

    # Rewards:
    # pos: How close the player's racket is to the ball and timing the impact correctly with the phase
    # win: winning the point
    # lose: losing the point penalty
    # bounce_in: Reward the player for hitting the ball inside the court
    # bounce_pos: Reward the player for difficult shots (near the edge of the court)
    reward_weights: {'pos': 10, 'win': 10, 'lose': -10, 'bounce_in': 5, 'bounce_pos': 1}
    ball_traj_out_x_file: data/ball_traj/ball_traj_out_x.npy
    ball_traj_out_y_file: data/ball_traj/ball_traj_out_y.npy

    obs_ball_traj_length: 10
    use_history_ball_obs: False
    ball_traj_file: data/ball_traj/ball_traj_in_dual.npy

    vae_action_scale: 1.5
    add_residual_dof: euler
    residual_dof_scale: 0.4
    aux_loss_specs: {'dof_res': 0.01}
    fix_head_orientation: True
    fix_two_hand_backhand_post: True

    vae_init_conditions_serve:  data/vae/vae_init_condition_federer_swing.pt
    vae_init_conditions_ready:  data/vae/vae_init_condition_federer_ready.pt
    
sim:
  substeps: 6
  none: 0

params:

  algo:
    name: selfplayer

  model:
    name: selfplayer

  network:
    name: selfplayer
    separate: True
    actor_net_type: 'style_cat1'
    latent_type: 'sphere'
    use_running_obs: True
    running_obs_type: ours

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.9
        fixed_sigma: True

    mlp:
      units: [1024, 1024, 512]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    disc:
      units: [1024, 1024, 512]
      activation: relu

      initializer:
        name: default

    enc:
      units: [1024, 512]
      activation: relu
      separate: False

      initializer:
        name: default

  load_checkpoint: False

  config:
    name: tennis_v1
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: False
    normalize_value: True
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-5
    lr_schedule: constant
    score_to_win: 20000
    max_epochs: 10
    save_best_after:  10
    save_frequency: 500
    print_stats: True
    entropy_coef: 0.0
    truncate_grads: True
    grad_norm: 50.0
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 2
    mini_epochs: 1
    critic_coef: 5
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 10
    clip_actions_val: 5.0
    pretrained_model_cp: results/kyrgios_bouncy_3/models/tennis_v1_latest.pth
    use_comet: False
